// get agenda constants
export const GET_AGENDA_LIST_REQUEST = "GET_AGENDA_LIST_REQUEST";
export const GET_AGENDA_LIST_SUCCESS = "GET_AGENDA_LIST_SUCCESS";
export const GET_AGENDA_LIST_FAIL = "GET_AGENDA_LIST_FAIL";

// add agenda constants
export const ADD_AGENDA_REQUEST = "ADD_AGENDA_REQUEST";
export const ADD_AGENDA_SUCCESS = "ADD_AGENDA_SUCCESS";
export const ADD_AGENDA_FAIL = "ADD_AGENDA_FAIL";

// delete agenda constants
export const DELETE_AGENDA_REQUEST = "DELETE_AGENDA_REQUEST";
export const DELETE_AGENDA_SUCCESS = "DELETE_AGENDA_SUCCESS";
export const DELETE_AGENDA_FAIL = "DELETE_AGENDA_FAIL";

// update agenda constants
export const UPDATE_AGENDA_REQUEST = "UPDATE_AGENDA_REQUEST";
export const UPDATE_AGENDA_SUCCESS = "UPDATE_AGENDA_SUCCESS";
export const UPDATE_AGENDA_FAIL = "UPDATE_AGENDA_FAIL";
